environment:
  matrix:
    - QTDIR: C:\Qt\5.11\msvc2015
      CMD_VCVARSALL: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x86'
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MSVC_PLATFORM: "x86"
    - QTDIR: C:\Qt\5.11\msvc2017_64
      CMD_VCVARSALL: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64'
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MSVC_PLATFORM: "x64"

configuration:
  - release

# Get the project submodules
# Set the environment variables and paths to make
install:
  - git submodule update --init --recursive
  - dir %QTDIR%
  - call %CMD_VCVARSALL%
  - set PATH=%PATH%;%QTDIR%\bin;%APPVEYOR_BUILD_FOLDER%\OpenCV\bin

# Run qmake
before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - qmake ..\temp\imageBeautify.pro


# Build the projects
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - cd build
  - nmake
  
  
after_build:
  - cd %APPVEYOR_BUILD_FOLDER%\build\release
  - mkdir release
  - cd release
  - xcopy %APPVEYOR_BUILD_FOLDER%\build\release\imageBeautify.exe %APPVEYOR_BUILD_FOLDER%\build\release\release\
  - windeployqt imageBeautify.exe
  

artifacts:
  - path: build\release\release\
    name: image_beautify_bin
  - path: temp\
    name: image_beautify_src

deploy:
  - provider: GitHub
    auth_token:
      secure: 0ITmy8HuewW3zTSS4Zfusi9wn6G2Hmq718SLrQNDiDFC89ZcrBrYSyE1gWQJ9Om2
    prerelease: true
